### ISSUE TITLE
 inverse_render.py  CUDAout of memory

### ISSUE THREAD

**Issue by molo32** [marcoamonteiro/pi-GAN#24]
i ​use a k80 gpu  when i run
`!python /content/pi-GAN/inverse_render.py /content/CelebA/generator.pth /content/face.png `

/```
usr/local/lib/python3.7/dist-packages/torchvision/transforms/transforms.py:258: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  "Argument interpolation should be of type InterpolationMode instead of int. "
Traceback (most recent call last):
  File "/content/pi-GAN/inverse_render.py", line 108, in <module>
    frame, _ = generator.forward_with_frequencies(w_frequencies + noise_w_frequencies + w_frequency_offsets, w_phase_shifts + noise_w_phase_shifts + w_phase_shift_offsets, **options)
  File "/content/pi-GAN/generators/generators.py", line 306, in forward_with_frequencies
    coarse_output = self.siren.forward_with_frequencies_phase_shifts(transformed_points, frequencies, phase_shifts, ray_directions=transformed_ray_directions_expanded).reshape(batch_size, img_size * img_size, num_steps, 4)
  File "/content/pi-GAN/siren/siren.py", line 212, in forward_with_frequencies_phase_shifts
    rbg = self.color_layer_sine(torch.cat([ray_directions, x], dim=-1), frequencies[..., -self.hidden_dim:], phase_shifts[..., -self.hidden_dim:])
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/pi-GAN/siren/siren.py", line 94, in forward
    return torch.sin(freq * x + phase_shift)
RuntimeError: CUDA out of memory. Tried to allocate 384.00 MiB (GPU 0; 11.17 GiB total capacity; 10.36 GiB already allocated; 377.81 MiB free; 10.37 GiB reserved in total by PyTorch)
```

**Comment by zhywanna** [comment]
Hi molo,

Did you find a way to figure it out ?
